name: Laravel CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
      - name: Install deps
        run: |
          composer install --prefer-dist --no-progress
          cp .env.example .env
          php artisan key:generate
      - name: Run tests
        run: php artisan test --parallel
